AllCops:
  NewCops: enable

Lint/TrailingCommaInAttributeDeclaration: # (new in 0.90)
  Enabled: true
Lint/MissingSuper:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInBlockArgs:
  Enabled: true
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/YodaExpression:
  Enabled: false
