#!/usr/bin/env ruby
# frozen_string_literal: true

require 'dry/cli'

require_relative 'app/merge_queue'

module Cli
  extend Dry::CLI::Registry

  class MergeQueue < Dry::CLI::Command
    option :auto, type: :boolean, default: false, desc: 'Run simulator automatically'
    option :persist_log, type: :boolean, default: false, desc: 'Keep all log messages on screen'
    option :features, type: :string, default: '3', desc: 'Number of features to create when --auto is true'
    option :rebase, type: :boolean, default: false, desc: 'Rebase when merging'

    def call(auto:, features:, persist_log:, rebase:)
      features = features.to_i
      ::MergeQueue.new(auto:, features:, persist_log:, rebase:)
    end
  end
end

Dry::CLI.new(Cli::MergeQueue).call
