#!/usr/bin/env ruby
# frozen_string_literal: true

require 'dry/cli'

require_relative 'app/merge_queue'

module Cli
  extend Dry::CLI::Registry

  class MergeQueue < Dry::CLI::Command
    desc 'Merge queue simulator'

    option :auto, type: :boolean, default: false, desc: 'Run simulator automatically'
    option :features, type: :string, default: '3', desc: "Number of features to create when --auto is true"

    def call(auto:, features:)
      features = features.to_i
      ::MergeQueue.new(auto:, features:)
    end
  end
end

Dry::CLI.new(Cli::MergeQueue).call
